import { SearchResultItem } from '@/types';

export const POPULAR_MOVIES_AND_TV: SearchResultItem[] = [
  // --- NEPALI CINEMA ---
  {
    externalId: 'np-loot-2012',
    type: 'movie',
    title: 'Loot',
    creator: 'Nischal Basnet',
    releaseYear: 2012,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/87/Loot_Poster.jpg',
    overview: 'In Kathmandu, Haku Kale plots a high-stakes bank robbery with four frustrated young men. A groundbreaking revolution in modern Nepali cinema.',
    genres: ['Crime', 'Thriller', 'Action', 'Nepali Cinema'],
    source: 'omdb' as any,
  },
  {
    externalId: 'np-pashupati-prasad',
    type: 'movie',
    title: 'Pashupati Prasad',
    creator: 'Dipendra K. Khanal',
    releaseYear: 2016,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a7/Pashupati_Prasad_poster.jpg',
    overview: 'After losing his parents in the 2015 earthquake, a young man travels to Kathmandu to earn 5 million rupees to clear his father’s debt, navigating survival around Pashupatinath temple.',
    genres: ['Social Drama', 'Satire', 'Nepali Cinema'],
    source: 'omdb' as any,
  },
  {
    externalId: 'np-pashupati-2',
    type: 'movie',
    title: 'Pashupati Prasad 2: Bhasme Don',
    creator: 'Dipendra K. Khanal',
    releaseYear: 2023,
    coverImage: 'https://blog.khalti.com/wp-content/uploads/2023/03/pashupati-prasad-2-bhasme-don-poster-711x1024.jpg',
    overview: 'Following the death of Pashupati Prasad, Bhasme Don struggles to establish his authority and identity in the changing terrain of Pashupatinath.',
    genres: ['Crime', 'Drama', 'Nepali Cinema'],
    source: 'omdb' as any,
  },
  {
    externalId: 'np-kabaddi',
    type: 'movie',
    title: 'Kabaddi',
    creator: 'Ram Babu Gurung',
    releaseYear: 2014,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/1b/Kabaddi_nepali_movie_poster.jpg',
    overview: 'Set in Mustang, Kazi, an aimless young man, schemes to marry his maternal cousin Maiya, while facing rivalry and rejection.',
    genres: ['Comedy', 'Romance', 'Drama', 'Nepali Cinema'],
    source: 'omdb' as any,
  },
  {
    externalId: 'np-kabaddi-4',
    type: 'movie',
    title: 'Kabaddi 4: The Final Match',
    creator: 'Ram Babu Gurung',
    releaseYear: 2022,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/82/Kabaddi_4_poster.jpg',
    overview: 'The definitive conclusion to Kazi’s bachelorhood saga, resolving his long-standing quest for love and purpose in the mountains.',
    genres: ['Comedy', 'Drama', 'Nepali Cinema'],
    source: 'omdb' as any,
  },
  {
    externalId: 'np-kalo-pothi',
    type: 'movie',
    title: 'Kalo Pothi: The Black Hen',
    creator: 'Min Bahadur Bham',
    releaseYear: 2015,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/52/Kalo_pothi_poster.jpg',
    overview: 'During the Nepalese civil war in a northern village, two young boys from different castes set off across fragile ceasefires to find a missing hen.',
    genres: ['Drama', 'War', 'Nepali Cinema'],
    source: 'omdb' as any,
  },
  {
    externalId: 'np-shambhala-2024',
    type: 'movie',
    title: 'Shambhala',
    creator: 'Min Bahadur Bham',
    releaseYear: 2024,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/4b/Shambhala_2024_film_poster.jpg',
    overview: 'In a high-Himalayan polyandrous community, pregnant Pema journeys into the frozen wilderness to find her traveling first husband. Berlin Film Festival Official Selection.',
    genres: ['Drama', 'Himalayas', 'Nepali Cinema'],
    source: 'omdb' as any,
  },
  {
    externalId: 'np-jatra',
    type: 'movie',
    title: 'Jatra',
    creator: 'Pradeep Bhattarai',
    releaseYear: 2016,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/49/Jatra_Poster.jpg',
    overview: 'Three innocent middle-class shopkeepers in Asan discover an abandoned sack of 30 million rupees, sparking frantic hilarity.',
    genres: ['Comedy', 'Crime', 'Nepali Cinema'],
    source: 'omdb' as any,
  },
  {
    externalId: 'np-chhakka-panja',
    type: 'movie',
    title: 'Chhakka Panja',
    creator: 'Deepa Shree Niraula',
    releaseYear: 2016,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/9/9c/Chhakka_panja_poster.jpg',
    overview: 'A sharp social satire highlighting remittance culture, marital mistrust, and youth migration from rural Nepal to the Gulf.',
    genres: ['Comedy', 'Social', 'Nepali Cinema'],
    source: 'omdb' as any,
  },
  {
    externalId: 'np-jaari',
    type: 'movie',
    title: 'Jaari',
    creator: 'Upendra Subba',
    releaseYear: 2023,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/30/Jaari_film_poster.jpg',
    overview: 'A deeply authentic representation of Limbu customary laws, marital separation, and reconciliation in rural eastern Nepal.',
    genres: ['Drama', 'Culture', 'Nepali Cinema'],
    source: 'omdb' as any,
  },
  {
    externalId: 'np-caravan-himalaya',
    type: 'movie',
    title: 'Caravan (Himalaya)',
    creator: 'Eric Valli',
    releaseYear: 1999,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/23/Himalaya_film_poster.jpg',
    overview: 'Generations clash in Dolpo as elderly Tinle leads a grueling yak caravan through treacherous Himalayan passes. Academy Award nominee.',
    genres: ['Adventure', 'Drama', 'Nepali Cinema'],
    source: 'omdb' as any,
  },
  {
    externalId: 'np-darpan-chhaya',
    type: 'movie',
    title: 'Darpan Chhaya',
    creator: 'Tulsi Ghimire',
    releaseYear: 2001,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/4f/Darpan_Chhaya.jpg',
    overview: 'The landmark Nepali romantic tragedy about friendship, unrequited love, and terminal illness featuring iconic songs.',
    genres: ['Romance', 'Musical', 'Nepali Cinema'],
    source: 'omdb' as any,
  },
  {
    externalId: 'np-the-odyssey',
    type: 'movie',
    title: 'The Odyssey',
    creator: 'Christopher Nolan',
    releaseYear: 2026,
    coverImage: 'https://m.media-amazon.com/images/M/MV5BNTcyNmJlZmQtNDUwYy00NDBjLTg1NGQtYTY2Y2UxMWM3NmI1XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
    overview: 'A cinematic reimagining of Homer’s ancient epic, navigating mythical perils on the treacherous sea voyage back to Ithaca.',
    genres: ['Action', 'Adventure', 'Fantasy'],
    source: 'omdb' as any,
  },
  {
    externalId: 'omdb-tt15239678',
    type: 'movie',
    title: 'Dune: Part Two',
    creator: 'Denis Villeneuve',
    releaseYear: 2024,
    coverImage: 'https://m.media-amazon.com/images/M/MV5BNTc0YmQxMjEtODI5MC00NDg0LWI4NDctOGE3N2U2MmViMWUxXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
    overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    source: 'omdb' as any,
  },
  {
    externalId: 'omdb-tt1375666',
    type: 'movie',
    title: 'Inception',
    creator: 'Christopher Nolan',
    releaseYear: 2010,
    coverImage: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_QL75_UX380_CR0,0,380,562_.jpg',
    overview: 'A thief who steals corporate secrets through dream-sharing is tasked with planting an idea into the mind of a CEO.',
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    source: 'omdb' as any,
  },
  {
    externalId: 'omdb-tt0816692',
    type: 'movie',
    title: 'Interstellar',
    creator: 'Christopher Nolan',
    releaseYear: 2014,
    coverImage: 'https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
    overview: 'When Earth faces extinction, astronauts travel through a wormhole near Saturn in search of a habitable world for humanity.',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    source: 'omdb' as any,
  },
  {
    externalId: 'omdb-tt15398776',
    type: 'movie',
    title: 'Oppenheimer',
    creator: 'Christopher Nolan',
    releaseYear: 2023,
    coverImage: 'https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZjg3YS00NmFiLWIyZmQtZTGCZjNmZjY4Zjg5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
    overview: 'The gripping story of J. Robert Oppenheimer and his role in the creation of the atomic bomb during WWII.',
    genres: ['Biography', 'Drama', 'History'],
    source: 'omdb' as any,
  },
  {
    externalId: 'omdb-tt6751668',
    type: 'movie',
    title: 'Parasite',
    creator: 'Bong Joon Ho',
    releaseYear: 2019,
    coverImage: 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZS00YzU4LWEyYmMtOGQ1NWFiZDAxNmQ1XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
    overview: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    genres: ['Drama', 'Thriller'],
    source: 'omdb' as any,
  },
  {
    externalId: 'omdb-tt1187043',
    type: 'movie',
    title: '3 Idiots',
    creator: 'Rajkumar Hirani',
    releaseYear: 2009,
    coverImage: 'https://m.media-amazon.com/images/M/MV5BNTkyOGVjMGEtNmQzZi00NzFlLTlhOWQtODYyMDc2ZGJmYzFhXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg',
    overview: 'Two friends search for their unconventional college companion Rancho while recalling how he inspired them to pursue excellence over success.',
    genres: ['Comedy', 'Drama', 'Bollywood'],
    source: 'omdb' as any,
  }
];

export const POPULAR_BOOKS: SearchResultItem[] = [
  // ─────────────────────────────────────────────────────────────
  // Prioritized English Bestsellers & Literary Classics (Worldwide)
  // ─────────────────────────────────────────────────────────────
  {
    externalId: "en-harry-potter-1",
    type: 'book',
    title: "Harry Potter and the Sorcerer's Stone",
    creator: "J.K. Rowling",
    releaseYear: 1997,
    coverImage: "https://covers.openlibrary.org/b/id/10521270-L.jpg",
    overview: "A young boy discovers on his eleventh birthday that he is the orphaned son of two powerful wizards and possesses unique magical powers.",
    genres: ["Fantasy","Magic","Adventure"],
    pageCount: 309,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-great-gatsby",
    type: 'book',
    title: "The Great Gatsby",
    creator: "F. Scott Fitzgerald",
    releaseYear: 1925,
    coverImage: "https://covers.openlibrary.org/b/id/10590366-L.jpg",
    overview: "Set in the summer of 1922 on Long Island, exploring themes of decadence, idealism, and the hollow promise of the American Dream.",
    genres: ["Classics","Literary Fiction","Roaring Twenties"],
    pageCount: 180,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-to-kill-mockingbird",
    type: 'book',
    title: "To Kill a Mockingbird",
    creator: "Harper Lee",
    releaseYear: 1960,
    coverImage: "https://covers.openlibrary.org/b/id/14351077-L.jpg",
    overview: "Lawyer Atticus Finch defends a Black man falsely accused of rape in a segregated Alabama town, viewed through the eyes of his young daughter Scout.",
    genres: ["Classics","Legal Drama","Pulitzer Prize"],
    pageCount: 323,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-1984",
    type: 'book',
    title: "1984",
    creator: "George Orwell",
    releaseYear: 1949,
    coverImage: "https://covers.openlibrary.org/b/id/9267242-L.jpg",
    overview: "In a totalitarian future under the watchful eye of Big Brother, Winston Smith dares to rebel through forbidden love and independent thought.",
    genres: ["Dystopian","Sci-Fi","Classics"],
    pageCount: 328,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-animal-farm",
    type: 'book',
    title: "Animal Farm",
    creator: "George Orwell",
    releaseYear: 1945,
    coverImage: "https://covers.openlibrary.org/b/id/11261342-L.jpg",
    overview: "A brilliant satirical fable depicting farm animals who overthrow their human master, only to see a ruthless totalitarian elite arise among the pigs.",
    genres: ["Satire","Political Allegory","Classics"],
    pageCount: 112,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-the-alchemist",
    type: 'book',
    title: "The Alchemist",
    creator: "Paulo Coelho",
    releaseYear: 1988,
    coverImage: "https://covers.openlibrary.org/b/id/7414780-L.jpg",
    overview: "An Andalusian shepherd boy named Santiago embarks on an epic journey to Egypt following his Personal Legend and discovering treasures within.",
    genres: ["Philosophy","Inspirational","Fiction"],
    pageCount: 197,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-catcher-rye",
    type: 'book',
    title: "The Catcher in the Rye",
    creator: "J.D. Salinger",
    releaseYear: 1951,
    coverImage: "https://covers.openlibrary.org/b/id/8235113-L.jpg",
    overview: "Holden Caulfield recounts two turbulent days in New York City after being expelled from prep school, wrestling with alienation and innocence.",
    genres: ["Classics","Coming of Age","Fiction"],
    pageCount: 234,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-brave-new-world",
    type: 'book',
    title: "Brave New World",
    creator: "Aldous Huxley",
    releaseYear: 1932,
    coverImage: "https://covers.openlibrary.org/b/id/9255566-L.jpg",
    overview: "A chilling prophetic vision of a genetically engineered world state driven by synthetic pleasure, consumer conditioning, and loss of humanity.",
    genres: ["Dystopian","Sci-Fi","Classics"],
    pageCount: 268,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-fahrenheit-451",
    type: 'book',
    title: "Fahrenheit 451",
    creator: "Ray Bradbury",
    releaseYear: 1953,
    coverImage: "https://covers.openlibrary.org/b/id/10103730-L.jpg",
    overview: "In a society where television rules and literature is outlawed, fireman Guy Montag begins to question his mission of burning illicit books.",
    genres: ["Dystopian","Sci-Fi","Classics"],
    pageCount: 249,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-project-hail-mary",
    type: 'book',
    title: "Project Hail Mary",
    creator: "Andy Weir",
    releaseYear: 2021,
    coverImage: "https://covers.openlibrary.org/b/id/12745300-M.jpg",
    overview: "Lone astronaut Ryland Grace wakes up from a coma with amnesia and must use scientific problem-solving to save Earth from an extinction-level solar crisis.",
    genres: ["Sci-Fi","Space","Hard Sci-Fi"],
    pageCount: 476,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-the-martian",
    type: 'book',
    title: "The Martian",
    creator: "Andy Weir",
    releaseYear: 2011,
    coverImage: "https://covers.openlibrary.org/b/id/10524458-M.jpg",
    overview: "Stranded alone on Mars by a fierce dust storm, astronaut Mark Watney fights for survival using botany, chemistry, and indomitable humor.",
    genres: ["Sci-Fi","Survival","Adventure"],
    pageCount: 369,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-three-body-problem",
    type: 'book',
    title: "The Three-Body Problem",
    creator: "Cixin Liu",
    releaseYear: 2008,
    coverImage: "https://covers.openlibrary.org/b/id/12843460-M.jpg",
    overview: "Against the backdrop of China’s Cultural Revolution, a secret military project sends signals into deep space, establishing contact with a dying alien civilization.",
    genres: ["Sci-Fi","Hard Sci-Fi","Hugo Award"],
    pageCount: 390,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-lord-rings",
    type: 'book',
    title: "The Lord of the Rings: The Fellowship of the Ring",
    creator: "J.R.R. Tolkien",
    releaseYear: 1954,
    coverImage: "https://covers.openlibrary.org/b/id/12887640-M.jpg",
    overview: "Young hobbit Frodo Baggins inherits the One Ring of the Dark Lord Sauron and begins the perilous quest across Middle-earth to destroy it in Mount Doom.",
    genres: ["Epic Fantasy","Adventure","Classics"],
    pageCount: 423,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-the-hobbit",
    type: 'book',
    title: "The Hobbit",
    creator: "J.R.R. Tolkien",
    releaseYear: 1937,
    coverImage: "https://covers.openlibrary.org/b/id/13175899-L.jpg",
    overview: "Bilbo Baggins is swept into an epic quest by wizard Gandalf and thirteen dwarves to reclaim the lost Kingdom of Erebor from the dragon Smaug.",
    genres: ["Fantasy","Adventure","Classics"],
    pageCount: 310,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-game-thrones",
    type: 'book',
    title: "A Game of Thrones",
    creator: "George R.R. Martin",
    releaseYear: 1996,
    coverImage: "https://covers.openlibrary.org/b/id/8406786-L.jpg",
    overview: "Noble dynasties vie ruthlessly for control of the Iron Throne of Westeros while an ancient winter darkness stirs beyond the monumental Wall.",
    genres: ["Epic Fantasy","Political Drama","Dark Fantasy"],
    pageCount: 694,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-psychology-money",
    type: 'book',
    title: "The Psychology of Money",
    creator: "Morgan Housel",
    releaseYear: 2020,
    coverImage: "https://covers.openlibrary.org/b/id/9269788-L.jpg",
    overview: "Doing well with money isn’t about what you know. It’s about how you behave. Timeless lessons on wealth, greed, and happiness.",
    genres: ["Finance","Psychology","Business"],
    pageCount: 256,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-deep-work",
    type: 'book',
    title: "Deep Work",
    creator: "Cal Newport",
    releaseYear: 2016,
    coverImage: "https://covers.openlibrary.org/b/id/10609312-L.jpg",
    overview: "The ability to focus without distraction on a cognitively demanding task is a superpower in our distracted knowledge economy.",
    genres: ["Productivity","Self-Help","Focus"],
    pageCount: 304,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-mans-search-meaning",
    type: 'book',
    title: "Man's Search for Meaning",
    creator: "Viktor E. Frankl",
    releaseYear: 1946,
    coverImage: "https://covers.openlibrary.org/b/id/7884782-L.jpg",
    overview: "Psychiatrist Viktor Frankl’s profound account of survival in Nazi death camps and the development of logotherapy: finding purpose through suffering.",
    genres: ["Psychology","Philosophy","Memoir"],
    pageCount: 165,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-meditations",
    type: 'book',
    title: "Meditations",
    creator: "Marcus Aurelius",
    releaseYear: 180,
    coverImage: "https://covers.openlibrary.org/b/id/8235282-L.jpg",
    overview: "The private spiritual and philosophical diary of Roman Emperor Marcus Aurelius, offering enduring stoic wisdom on duty, resilience, and inner peace.",
    genres: ["Philosophy","Stoicism","Classics"],
    pageCount: 254,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-steve-jobs",
    type: 'book',
    title: "Steve Jobs",
    creator: "Walter Isaacson",
    releaseYear: 2011,
    coverImage: "https://covers.openlibrary.org/b/id/10521271-L.jpg",
    overview: "The definitive, unvarnished biography of the visionary Apple co-founder who revolutionized computers, animated movies, music, phones, and tablet computing.",
    genres: ["Biography","Tech","Innovation"],
    pageCount: 656,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-shoe-dog",
    type: 'book',
    title: "Shoe Dog: A Memoir by the Creator of Nike",
    creator: "Phil Knight",
    releaseYear: 2016,
    coverImage: "https://covers.openlibrary.org/b/id/8231992-L.jpg",
    overview: "Nike founder Phil Knight illuminates his journey from borrowing $50 from his father to building one of the world’s most iconic sports empires.",
    genres: ["Memoir","Business","Inspirational"],
    pageCount: 400,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-rich-dad",
    type: 'book',
    title: "Rich Dad Poor Dad",
    creator: "Robert T. Kiyosaki",
    releaseYear: 1997,
    coverImage: "https://covers.openlibrary.org/b/id/12698741-L.jpg",
    overview: "Explodes the myth that you need to earn a high income to become rich, contrasting the mindsets of two fathers on assets, liabilities, and financial literacy.",
    genres: ["Personal Finance","Investing","Bestseller"],
    pageCount: 336,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-clean-code",
    type: 'book',
    title: "Clean Code: A Handbook of Agile Software Craftsmanship",
    creator: "Robert C. Martin",
    releaseYear: 2008,
    coverImage: "https://covers.openlibrary.org/b/id/8314134-L.jpg",
    overview: "The legendary guide for professional software developers on writing maintainable, readable, and elegant software.",
    genres: ["Computer Science","Software Engineering","Programming"],
    pageCount: 464,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-silent-patient",
    type: 'book',
    title: "The Silent Patient",
    creator: "Alex Michaelides",
    releaseYear: 2019,
    coverImage: "https://covers.openlibrary.org/b/id/8232001-L.jpg",
    overview: "Alicia Berenson shoots her husband five times in the face and never speaks another word. Psychotherapist Theo Faber is determined to unravel the truth.",
    genres: ["Psychological Thriller","Mystery","Suspense"],
    pageCount: 336,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-shining",
    type: 'book',
    title: "The Shining",
    creator: "Stephen King",
    releaseYear: 1977,
    coverImage: "https://covers.openlibrary.org/b/id/10582046-L.jpg",
    overview: "Jack Torrance takes a winter caretaker job at the isolated Overlook Hotel with his wife and telepathic son Danny, where malevolent forces slowly consume his sanity.",
    genres: ["Horror","Psychological Thriller","Classics"],
    pageCount: 447,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-frankenstein",
    type: 'book',
    title: "Frankenstein",
    creator: "Mary Shelley",
    releaseYear: 1818,
    coverImage: "https://covers.openlibrary.org/b/id/8739161-L.jpg",
    overview: "Young scientist Victor Frankenstein creates a sentient creature in an unorthodox scientific experiment, unleashing tragic and devastating consequences.",
    genres: ["Gothic Horror","Sci-Fi","Classics"],
    pageCount: 280,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-dracula",
    type: 'book',
    title: "Dracula",
    creator: "Bram Stoker",
    releaseYear: 1897,
    coverImage: "https://covers.openlibrary.org/b/id/8231993-L.jpg",
    overview: "The seminal epistolary horror novel introducing Count Dracula’s attempt to move from Transylvania to England to spread the undead curse.",
    genres: ["Gothic Horror","Vampires","Classics"],
    pageCount: 418,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-dorian-gray",
    type: 'book',
    title: "The Picture of Dorian Gray",
    creator: "Oscar Wilde",
    releaseYear: 1890,
    coverImage: "https://covers.openlibrary.org/b/id/8913988-L.jpg",
    overview: "Dorian Gray trades his soul for eternal youth and beauty, while a hidden portrait in his attic bears the grotesque marks of his sins and hedonism.",
    genres: ["Philosophical Fiction","Gothic","Classics"],
    pageCount: 272,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-crime-punishment",
    type: 'book',
    title: "Crime and Punishment",
    creator: "Fyodor Dostoevsky",
    releaseYear: 1866,
    coverImage: "https://covers.openlibrary.org/b/id/8232004-L.jpg",
    overview: "Impoverished ex-student Raskolnikov formulates a theory of extraordinary men and murders a pawnbroker, only to descend into a feverish psychological torment.",
    genres: ["Psychological Fiction","Philosophy","Classics"],
    pageCount: 671,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-book-thief",
    type: 'book',
    title: "The Book Thief",
    creator: "Markus Zusak",
    releaseYear: 2005,
    coverImage: "https://covers.openlibrary.org/b/id/8232005-L.jpg",
    overview: "Narrated by Death, a young foster girl in Nazi Germany finds solace in stealing books and sharing them with her neighbors and a hidden Jewish fist-fighter.",
    genres: ["Historical Fiction","Drama","Classics"],
    pageCount: 552,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-kite-runner",
    type: 'book',
    title: "The Kite Runner",
    creator: "Khaled Hosseini",
    releaseYear: 2003,
    coverImage: "https://covers.openlibrary.org/b/id/8232006-L.jpg",
    overview: "An Afghan man seeks redemption in California decades after betraying his loyal childhood friend in pre-Soviet Kabul.",
    genres: ["Historical Fiction","Drama","Contemporary"],
    pageCount: 371,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-thousand-splendid-suns",
    type: 'book',
    title: "A Thousand Splendid Suns",
    creator: "Khaled Hosseini",
    releaseYear: 2007,
    coverImage: "https://covers.openlibrary.org/b/id/8232007-L.jpg",
    overview: "The unforgettable story of two generations of Afghan women brought together by tragedy and bound by an unbreakable bond of sacrifice.",
    genres: ["Historical Fiction","Drama","Contemporary"],
    pageCount: 419,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-crawdads-sing",
    type: 'book',
    title: "Where the Crawdads Sing",
    creator: "Delia Owens",
    releaseYear: 2018,
    coverImage: "https://covers.openlibrary.org/b/id/8232008-L.jpg",
    overview: "Kya Clark, the barefoot \"Marsh Girl\", survives alone in the North Carolina marshes until she is accused of murdering a town celebrity.",
    genres: ["Mystery","Fiction","Nature"],
    pageCount: 384,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-midnight-library",
    type: 'book',
    title: "The Midnight Library",
    creator: "Matt Haig",
    releaseYear: 2020,
    coverImage: "https://covers.openlibrary.org/b/id/10433246-L.jpg",
    overview: "Between life and death sits a library containing infinite books, each representing an alternate life Nora Seed could have lived if she had made different choices.",
    genres: ["Fantasy","Philosophical","Contemporary"],
    pageCount: 304,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-normal-people",
    type: 'book',
    title: "Normal People",
    creator: "Sally Rooney",
    releaseYear: 2018,
    coverImage: "https://covers.openlibrary.org/b/id/8231856-L.jpg",
    overview: "Follows the intricate, magnetic, and complicated relationship between Connell and Marianne across their university years at Trinity College Dublin.",
    genres: ["Contemporary","Romance","Literary Fiction"],
    pageCount: 273,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-foundation",
    type: 'book',
    title: "Foundation",
    creator: "Isaac Asimov",
    releaseYear: 1951,
    coverImage: "https://covers.openlibrary.org/b/id/8231991-L.jpg",
    overview: "Mathematician Hari Seldon develops psychohistory to predict the imminent fall of the Galactic Empire and founds a sanctuary of knowledge to shorten the dark age.",
    genres: ["Sci-Fi","Space Opera","Classics"],
    pageCount: 255,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-neuromancer",
    type: 'book',
    title: "Neuromancer",
    creator: "William Gibson",
    releaseYear: 1984,
    coverImage: "https://covers.openlibrary.org/b/id/9269962-L.jpg",
    overview: "Washed-up computer hacker Case is hired by a shadowy operative for one last cyber-heist targeting an all-powerful artificial intelligence orbiting Earth.",
    genres: ["Cyberpunk","Sci-Fi","Classic"],
    pageCount: 271,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-klara-and-sun",
    type: 'book',
    title: "Klara and the Sun",
    creator: "Kazuo Ishiguro",
    releaseYear: 2021,
    coverImage: "https://covers.openlibrary.org/b/id/10389364-L.jpg",
    overview: "Klara, an Artificial Friend with outstanding observational qualities, watches human customers from her store window while seeking to understand what it means to love.",
    genres: ["Sci-Fi","Literary Fiction","AI"],
    pageCount: 303,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-cant-hurt-me",
    type: 'book',
    title: "Can't Hurt Me: Master Your Mind and Defy the Odds",
    creator: "David Goggins",
    releaseYear: 2018,
    coverImage: "https://covers.openlibrary.org/b/id/11145163-L.jpg",
    overview: "Navy SEAL David Goggins shares his astonishing life story and the 40% Rule, proving that most people tap into only a fraction of their mental endurance.",
    genres: ["Memoir","Motivation","Self-Help"],
    pageCount: 364,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-48-laws-power",
    type: 'book',
    title: "The 48 Laws of Power",
    creator: "Robert Greene",
    releaseYear: 1998,
    coverImage: "https://covers.openlibrary.org/b/id/8315576-L.jpg",
    overview: "Three millennia of the history of power synthesized into 48 ruthless laws drawn from Machiavelli, Sun Tzu, and Carl von Clausewitz.",
    genres: ["Psychology","Strategy","Self-Help"],
    pageCount: 452,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-courage-disliked",
    type: 'book',
    title: "The Courage to Be Disliked",
    creator: "Ichiro Kishimi & Fumitake Koga",
    releaseYear: 2013,
    coverImage: "https://covers.openlibrary.org/b/id/8771485-L.jpg",
    overview: "Drawing on Adlerian psychology, a philosopher and a young youth debate how to break free from past trauma, interpersonal burdens, and societal expectations.",
    genres: ["Philosophy","Psychology","Self-Help"],
    pageCount: 288,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-outliers",
    type: 'book',
    title: "Outliers: The Story of Success",
    creator: "Malcolm Gladwell",
    releaseYear: 2008,
    coverImage: "https://covers.openlibrary.org/b/id/8226191-L.jpg",
    overview: "Explores why high achievers succeed, examining culture, family, generation, and the idiosyncratic upbringing behind world-class outliers.",
    genres: ["Psychology","Sociology","Non-Fiction"],
    pageCount: 309,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-cosmos",
    type: 'book',
    title: "Cosmos",
    creator: "Carl Sagan",
    releaseYear: 1980,
    coverImage: "https://covers.openlibrary.org/b/id/8235288-L.jpg",
    overview: "The legendary exploration of the universe, tracing fifteen billion years of cosmic evolution that transformed matter into consciousness.",
    genres: ["Science","Astronomy","Cosmology"],
    pageCount: 365,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-brief-history-time",
    type: 'book',
    title: "A Brief History of Time",
    creator: "Stephen Hawking",
    releaseYear: 1988,
    coverImage: "https://covers.openlibrary.org/b/id/8228694-L.jpg",
    overview: "Theoretical physicist Stephen Hawking explores the Big Bang, black holes, light cones, and the quest for a unified theory of the cosmos.",
    genres: ["Science","Physics","Cosmology"],
    pageCount: 212,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-educated",
    type: 'book',
    title: "Educated",
    creator: "Tara Westover",
    releaseYear: 2018,
    coverImage: "https://covers.openlibrary.org/b/id/9269801-L.jpg",
    overview: "Born to survivalist parents in the mountains of Idaho, a young woman enters a classroom for the first time at seventeen and achieves a PhD at Cambridge.",
    genres: ["Memoir","Biography","Non-Fiction"],
    pageCount: 352,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-pragmatic-programmer",
    type: 'book',
    title: "The Pragmatic Programmer",
    creator: "Andrew Hunt & David Thomas",
    releaseYear: 1999,
    coverImage: "https://covers.openlibrary.org/b/id/9255567-L.jpg",
    overview: "Cuts through the increasing specialization of modern software development to examine the core process of crafting flexible, readable code.",
    genres: ["Software Engineering","Technology","Career"],
    pageCount: 352,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-da-vinci-code",
    type: 'book',
    title: "The Da Vinci Code",
    creator: "Dan Brown",
    releaseYear: 2003,
    coverImage: "https://covers.openlibrary.org/b/id/8235287-L.jpg",
    overview: "Symbologist Robert Langdon and cryptologist Sophie Neveu unravel a trail of clues embedded in the works of Leonardo da Vinci while being pursued across Paris.",
    genres: ["Mystery","Thriller","Historical Fiction"],
    pageCount: 454,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-gone-girl",
    type: 'book',
    title: "Gone Girl",
    creator: "Gillian Flynn",
    releaseYear: 2012,
    coverImage: "https://covers.openlibrary.org/b/id/8235286-L.jpg",
    overview: "On the morning of their fifth wedding anniversary, Nick Dunne discovers his beautiful wife Amy has disappeared, embroiling him in an endless media circus.",
    genres: ["Psychological Thriller","Mystery","Suspense"],
    pageCount: 432,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-and-then-none",
    type: 'book',
    title: "And Then There Were None",
    creator: "Agatha Christie",
    releaseYear: 1939,
    coverImage: "https://covers.openlibrary.org/b/id/8235285-L.jpg",
    overview: "Ten strangers are lured to an isolated island mansion off the Devon coast by an eccentric host, where they are murdered one by one according to a nursery rhyme.",
    genres: ["Mystery","Crime","Classics"],
    pageCount: 272,
    source: 'openlibrary' as any,
  },
  {
    externalId: "en-hound-baskervilles",
    type: 'book',
    title: "The Hound of the Baskervilles",
    creator: "Arthur Conan Doyle",
    releaseYear: 1902,
    coverImage: "https://covers.openlibrary.org/b/id/8235284-L.jpg",
    overview: "Sherlock Holmes and Dr. Watson investigate the mysterious death of Sir Charles Baskerville and the legend of a diabolical hound terrorizing Dartmoor.",
    genres: ["Mystery","Detective","Classics"],
    pageCount: 256,
    source: 'openlibrary' as any,
  },
  // ─────────────────────────────────────────────────────────────
  // 1. Contemporary Psychological & Youth Fiction
  // ─────────────────────────────────────────────────────────────
  {
    externalId: 'np-ek-sarko-maya',
    type: 'book',
    title: 'Ek Sarko Maya (एक सर्को माया)',
    creator: 'G.S. Poudel / Paudel (जी.एस. पौडेल)',
    releaseYear: 2018,
    coverImage: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1533749218i/41072786.jpg',
    overview: 'Deep psychological fiction dealing with human obsession, escapism, emotional void, and existential illusion in contemporary life.',
    genres: ['Nepali Literature', 'Psychological Fiction', 'Philosophy'],
    pageCount: 428,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-pahelpur',
    type: 'book',
    title: 'Pahelpur (पहेँलपुर)',
    creator: 'G.S. Poudel / Paudel (जी.एस. पौडेल)',
    releaseYear: 2021,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/Pahelpur_by-GS_Paudel-thumbnail-280x405-70.jpg',
    overview: 'Surrealist and psychological novel tracing themes of identity, social deceit, self-perception, and existential struggle.',
    genres: ['Nepali Literature', 'Surrealism', 'Psychological Fiction'],
    pageCount: 464,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-summer-love',
    type: 'book',
    title: 'Summer Love (समर लभ)',
    creator: 'Subin Bhattarai (सुबिन भट्टराई)',
    releaseYear: 2012,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d9/Summer_Love_%28novel%29.jpg',
    overview: 'A landmark modern romance sensation among Nepali youth following the college love story between Atit and Saaya at Central Campus, Kirtipur.',
    genres: ['Nepali Literature', 'Romance', 'Youth Fiction'],
    pageCount: 278,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-saya',
    type: 'book',
    title: 'Saaya / Saya (साया)',
    creator: 'Subin Bhattarai (सुबिन भट्टराई)',
    releaseYear: 2014,
    coverImage: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1407659398i/22889351.jpg',
    overview: 'The beloved sequel concluding the Atit-Saaya arc. Atit journeys to Norway in a passionate, turbulent attempt to heal the wounds of their past.',
    genres: ['Nepali Literature', 'Romance', 'Drama'],
    pageCount: 312,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-monsoon',
    type: 'book',
    title: 'Monsoon (मनसुन)',
    creator: 'Subin Bhattarai (सुबिन भट्टराई)',
    releaseYear: 2016,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/monsoon_jixxICF-thumbnail-280x405-70.jpg',
    overview: 'An urban relationship drama delving into emotional complexities, vulnerability, heartbreak, and unpredictable human connections in modern Kathmandu.',
    genres: ['Nepali Literature', 'Contemporary Romance', 'Drama'],
    pageCount: 298,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-ejoria',
    type: 'book',
    title: 'Ijoriya / Ejoria (इजोरिया)',
    creator: 'Subin Bhattarai (सुबिन भट्टराई)',
    releaseYear: 2022,
    coverImage: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1776411272i/127045337.jpg',
    overview: 'Set across the Mithila region and Kathmandu, Ijoriya captures deep familial affection, sibling dynamics, and forgiveness under the moonlight of Tarai.',
    genres: ['Nepali Literature', 'Fiction', 'Family Drama'],
    pageCount: 334,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-karodau-kastoori',
    type: 'book',
    title: 'Karodau Kastoori (करोडौँ कस्तूरी)',
    creator: 'Amar Neupane (अमर न्यौपाने)',
    releaseYear: 2015,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/karodau-kastoori_ytY7Owh-thumbnail-280x405-70.jpg',
    overview: 'An imaginative tribute to iconic artist Hari Bansha Acharya, exploring latent talent, purpose, and the realization that every soul carries a treasure within.',
    genres: ['Nepali Literature', 'Inspirational Fiction', 'Drama'],
    pageCount: 380,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-gulabi-umer',
    type: 'book',
    title: 'Gulabi Umer (गुलाबी उमेर)',
    creator: 'Amar Neupane (अमर न्यौपाने)',
    releaseYear: 2019,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/gulabi-umer_gVXYUNu-thumbnail-280x405-70.jpg',
    overview: 'A delicate and candid coming-of-age exploration of adolescent psychology, emotional turbulence, physical awakening, and dreams in modern Nepal.',
    genres: ['Nepali Literature', 'Coming of Age', 'Psychological'],
    pageCount: 224,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-seto-dharti',
    type: 'book',
    title: 'Seto Dharti (सेतो धरती)',
    creator: 'Amar Neupane (अमर न्यौपाने)',
    releaseYear: 2011,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/seto-dharti_FvneEev-thumbnail-280x405-70.jpg',
    overview: 'Madan Puraskar-winning poignant masterpiece recounting the heartbreaking plight, societal cruelty, and resilience of Tara, a child widow in Devghat.',
    genres: ['Nepali Literature', 'Historical Fiction', 'Madan Puraskar'],
    pageCount: 384,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-karnali-blues',
    type: 'book',
    title: 'Karnali Blues (कर्णाली ब्लुज)',
    creator: 'Buddhisagar (बुद्धिसागर)',
    releaseYear: 2010,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/karnali-blues_fsID4LL-thumbnail-280x405-70.jpg',
    overview: 'A tender masterpiece chronicling the unbreakable father-son bond through Brisha Bahadur\'s memories of childhood in western Nepal\'s Far-West.',
    genres: ['Nepali Literature', 'Coming of Age', 'Memoir Fiction'],
    pageCount: 448,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-firfire',
    type: 'book',
    title: 'Phirphire / Firfire (फिरफिरे)',
    creator: 'Buddhisagar (बुद्धिसागर)',
    releaseYear: 2016,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/phirphirey_YhENs6i-thumbnail-280x405-70.jpg',
    overview: 'A rich tapestry of village folklore, lifelong friendships, rural superstitions, and bittersweet childhood nostalgia in the Tarai plains.',
    genres: ['Nepali Literature', 'Rural Realism', 'Drama'],
    pageCount: 544,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-eklo',
    type: 'book',
    title: 'Eklo (एक्लो)',
    creator: 'Buddhisagar (बुद्धिसागर)',
    releaseYear: 2022,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/EKLO_Cover_Final_Final3-thumbnail-280x405-70.jpg',
    overview: 'A poignant narrative on modern urban solitude, existential longing, self-confrontation, and the search for warmth in a bustling city.',
    genres: ['Nepali Literature', 'Psychological Fiction', 'Contemporary'],
    pageCount: 480,
    source: 'openlibrary' as any,
  },

  // ─────────────────────────────────────────────────────────────
  // 2. Social Realism, Regional Voice, and Marginalized Communities
  // ─────────────────────────────────────────────────────────────
  {
    externalId: 'np-sallipir',
    type: 'book',
    title: 'Sallipir (सल्लिपीर)',
    creator: 'Nayan Raj Pandey (नयनराज पाण्डे)',
    releaseYear: 2016,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/sallipir_NPoW6YC-thumbnail-280x405-70.jpg',
    overview: 'An evocative narrative set in the Solukhumbu highlands portraying Sherpa customs, climatic cruelty, yak herding, and spiritual resilience.',
    genres: ['Nepali Literature', 'Social Realism', 'Himalayan Culture'],
    pageCount: 318,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-loo',
    type: 'book',
    title: 'Loo (लू)',
    creator: 'Nayan Raj Pandey (नयनराज पाण्डे)',
    releaseYear: 2012,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/loo_fAc5gju-thumbnail-280x405-70.jpg',
    overview: 'Gritty portrayal of life along the scorching Nepal-India border, capturing poverty, political betrayal, and human dignity against the harsh dry winds of Loo.',
    genres: ['Nepali Literature', 'Social Realism', 'Borderland Drama'],
    pageCount: 376,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-ghamkiri',
    type: 'book',
    title: 'Ghamkiri (घामकिरी)',
    creator: 'Nayan Raj Pandey (नयनराज पाण्डे)',
    releaseYear: 2014,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/ghaamkiri-thumbnail-280x405-70.jpg',
    overview: 'Tracing ordinary human hopes, intricate psychological turns, and changing socio-cultural realities in suburban and rural Nepal.',
    genres: ['Nepali Literature', 'Realism', 'Drama'],
    pageCount: 310,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-ular',
    type: 'book',
    title: 'Ular (उलार)',
    creator: 'Nayan Raj Pandey (नयनराज पाण्डे)',
    releaseYear: 1996,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/ular-thumbnail-280x405-70.jpg',
    overview: 'Sharp satirical novella on political exploitation, following tonga-driver Shanti whose horse and livelihood are callously used as political fodder.',
    genres: ['Nepali Literature', 'Novella', 'Social Satire'],
    pageCount: 120,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-damini-bhir',
    type: 'book',
    title: 'Damini Bhir (दामिनी भीर)',
    creator: 'Rajan Mukarung (राजन मुकारुङ)',
    releaseYear: 2013,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/Damini_Bhir_front-thumbnail-280x405-70.jpg',
    overview: 'Madan Puraskar winner interweaving Kirat folklore, ethnic identity, indigenous philosophy, and the socio-political disillusionment of post-conflict Nepal.',
    genres: ['Nepali Literature', 'Indigenous Voice', 'Madan Puraskar'],
    pageCount: 290,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-yambunera',
    type: 'book',
    title: 'Yambunera (याम्बुनेर)',
    creator: 'Bina Theeng Tamang (बिना थिङ तामाङ)',
    releaseYear: 2020,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/Yambunera_by_Bina_Theeng_-_front-thumbnail-280x405-70.jpg',
    overview: 'A compelling collection of short stories illuminating the lives, resilience, and quiet battles of Tamang women living on the margins of Kathmandu.',
    genres: ['Nepali Literature', 'Short Stories', 'Feminism'],
    pageCount: 208,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-nathiya',
    type: 'book',
    title: 'Nathiya (नथिया)',
    creator: 'Saraswati Pratikshya (सरस्वती प्रतीक्षा)',
    releaseYear: 2018,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/_Nathiya_Book_By_Saraswati_Pratikshya_Cover_-thumbnail-280x405.PNG',
    overview: 'Groundbreaking novel chronicling the systemic subjugation, forced sex work, and fierce survival instincts of Badi women in western Nepal.',
    genres: ['Nepali Literature', 'Historical Realism', 'Feminism'],
    pageCount: 282,
    source: 'openlibrary' as any,
  },

  // ─────────────────────────────────────────────────────────────
  // 3. Political Conflict, Civil War & Social Transformation
  // ─────────────────────────────────────────────────────────────
  {
    externalId: 'np-palpasa-cafe',
    type: 'book',
    title: 'Palpasa Café (पल्पसा क्याफे)',
    creator: 'Narayan Wagle (नारायण वाग्ले)',
    releaseYear: 2005,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/19/Palpasa_Cafe_by_Narayan_Wagle.jpg',
    overview: 'Defining anti-war novel depicting the harrowing impact of the Maoist insurgency on ordinary civilians through the eyes of painter Drishya.',
    genres: ['Nepali Literature', 'Anti-War', 'Madan Puraskar'],
    pageCount: 246,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-mayur-times',
    type: 'book',
    title: 'Mayur Times (मयूर टाइम्स)',
    creator: 'Narayan Wagle (नारायण वाग्ले)',
    releaseYear: 2010,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/Mayur_Times_by_Narayan_Wagle-thumbnail-280x405-70.jpg',
    overview: 'Set during Nepal\'s post-war transitional crisis and Terai unrest, following journalists Parag and Lisara navigating regional tensions and hope.',
    genres: ['Nepali Literature', 'Political Fiction', 'Journalism'],
    pageCount: 231,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-urgenko-ghoda',
    type: 'book',
    title: 'Urgenko Ghoda (उर्गेनको घोडा)',
    creator: 'Yug Pathak (युग पाठक)',
    releaseYear: 2009,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/urgenko-ghoda_p3z1nal-thumbnail-280x405-70.jpg',
    overview: 'A powerful counter-narrative of state suppression and indigenous resistance, deconstructing dominant national mythologies through Tamang history.',
    genres: ['Nepali Literature', 'Historical Resistance', 'Social Justice'],
    pageCount: 271,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-aaithan',
    type: 'book',
    title: 'Aaithan / Aithan (ऐँठन)',
    creator: 'Bibek Ojha (विवेक ओझा)',
    releaseYear: 2022,
    coverImage: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1694191796i/198804978.jpg',
    overview: 'Madan Puraskar-winning anti-war novel illustrating the psychological trauma, grief, and generational scars inflicted on civilians by the decade-long civil war.',
    genres: ['Nepali Literature', 'Historical Fiction', 'Madan Puraskar'],
    pageCount: 380,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-khalangama-hamala',
    type: 'book',
    title: 'Khalangama Hamala (खलङ्गामा हमला)',
    creator: 'Radha Paudel (राधा पौडेल)',
    releaseYear: 2013,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/Khalanga_ma_Hamala_by_Radha_Paudel-thumbnail-280x405-70.jpg',
    overview: 'Madan Puraskar-winning diary of a nurse surviving the terrifying Maoist midnight assault on Khalanga, Jumla, highlighting compassion amid devastation.',
    genres: ['Nepali Literature', 'War Memoir', 'Madan Puraskar'],
    pageCount: 144,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-prayogshala',
    type: 'book',
    title: 'Prayogshala (प्रयोगशाला)',
    creator: 'Sudheer Sharma (सुधीर शर्मा)',
    releaseYear: 2013,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/Prayogshala-thumbnail-280x405.png',
    overview: 'Rigorous investigative non-fiction uncovering the geopolitical machinations, intelligence games, and palace-rebel dynamics that shaped contemporary Nepal.',
    genres: ['Non-Fiction', 'Geopolitics', 'Nepali Politics'],
    pageCount: 418,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-mukam-ranamaidan',
    type: 'book',
    title: 'Mukam Ranamaidan (मुकाम रणमैदान)',
    creator: 'Mohan Mainali (मोहन मैनाली)',
    releaseYear: 2023,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/mukam-raramaidan-f-thumbnail-280x405-70.jpg',
    overview: 'Madan Puraskar-winning historical masterpiece recounting the courage, sacrifice, and strategic realities of the Anglo-Nepal War battlefields.',
    genres: ['History', 'Military Non-Fiction', 'Madan Puraskar'],
    pageCount: 320,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-raktakunda',
    type: 'book',
    title: 'Raktakunda / Darbar Hatyakanda (रक्तकुण्ड)',
    creator: 'Krishna Abiral (कृष्ण अविरल)',
    releaseYear: 2006,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/raktakunda-thumbnail-280x405-70.jpg',
    overview: 'Gripping speculative and investigative novel centered around the 2001 Narayanhiti royal palace massacre and the resulting political earthquake.',
    genres: ['Nepali Literature', 'Political Thriller', 'History'],
    pageCount: 142,
    source: 'openlibrary' as any,
  },

  // ─────────────────────────────────────────────────────────────
  // 4. Timeless Classics & Literary Pillars
  // ─────────────────────────────────────────────────────────────
  {
    externalId: 'np-muna-madan',
    type: 'book',
    title: 'Muna Madan (मुना मदन)',
    creator: 'Laxmi Prasad Devkota (लक्ष्मीप्रसाद देवकोटा)',
    releaseYear: 1936,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/1d/Muna_Madan_-_book_cover.jpg',
    overview: 'Nepal\'s most revered epic ballad in Jhyaure metre, exalting compassion over caste ("Manis thulo dilale hunchha") and the tragic human cost of migration.',
    genres: ['Nepali Literature', 'Epic Poetry', 'Khandakavya'],
    pageCount: 68,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-shirishko-phool',
    type: 'book',
    title: 'Shirishko Phool (The Blue Mimosa / शिरिषको फूल)',
    creator: 'Parijat (पारिजात)',
    releaseYear: 1964,
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Shirish_ko_Phool.jpg',
    overview: 'A groundbreaking existential novel portraying disillusioned ex-soldier Suyog Bir and enigmatic Sakambari, probing the futility of desires.',
    genres: ['Nepali Literature', 'Existentialism', 'Madan Puraskar'],
    pageCount: 112,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-anido-pahadsangai',
    type: 'book',
    title: 'Anido Pahadsangai (अनिदो पहाडसँगै)',
    creator: 'Parijat (पारिजात)',
    releaseYear: 1982,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/Anido_pahad_sangai-thumbnail-280x405-70.jpg',
    overview: 'Powerful political novel capturing peasant rebellions, underground communist resistance, and collective hope against state tyranny.',
    genres: ['Nepali Literature', 'Political Fiction', 'Social Justice'],
    pageCount: 250,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-sumnima',
    type: 'book',
    title: 'Sumnima (सुम्निमा)',
    creator: 'B.P. Koirala (विश्वेश्वरप्रसाद कोइराला)',
    releaseYear: 1969,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/Sumnima_by_BP_Koirala_S3QXAoY-thumbnail-280x405-70.jpg',
    overview: 'Masterful philosophical novel exploring the dialectic between Aryan ascetic spirituality (Somdatta) and indigenous Kirat earthly materialism (Sumnima).',
    genres: ['Nepali Literature', 'Philosophy', 'Psychological Fiction'],
    pageCount: 205,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-teen-ghumti',
    type: 'book',
    title: 'Teen Ghumti (तीन घुम्ती)',
    creator: 'B.P. Koirala (विश्वेश्वरप्रसाद कोइराला)',
    releaseYear: 1968,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/Teen_Ghumti-thumbnail-280x405-70.jpg',
    overview: 'Psychological exploration of female autonomy, revolutionary idealism, and moral dilemmas through three pivotal decisions in protagonist Indu\'s life.',
    genres: ['Nepali Literature', 'Psychological Realism', 'Feminist Agency'],
    pageCount: 128,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-modiain',
    type: 'book',
    title: 'Modiain (मोदिआइन)',
    creator: 'B.P. Koirala (विश्वेश्वरप्रसाद कोइराला)',
    releaseYear: 1980,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/Modiaain_-_BP_Koirala-thumbnail-280x405-70.jpg',
    overview: 'A profound pacifist critique reinterpreting the devastating slaughter of the Mahabharata war through the humble eyes of a grocer\'s wife.',
    genres: ['Nepali Literature', 'Anti-War Novella', 'Philosophical'],
    pageCount: 74,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-hitler-ra-yahudi',
    type: 'book',
    title: 'Hitler ra Yahudi (हिटलर र यहुदी)',
    creator: 'B.P. Koirala (विश्वेश्वरप्रसाद कोइराला)',
    releaseYear: 1983,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/Hitler_ra_Yahudi-thumbnail-280x405-70.jpg',
    overview: 'B.P. Koirala\'s meditation on totalitarian cruelty versus individual liberty and love, set against the grim reality of Nazi concentration camps.',
    genres: ['Nepali Literature', 'Historical Fiction', 'Existentialism'],
    pageCount: 298,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-seto-bagh',
    type: 'book',
    title: 'Seto Bagh (सेतो बाघ)',
    creator: 'Diamond Shumsher Rana (डायमण्ड शमशेर राणा)',
    releaseYear: 1973,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/seto_bagh_f-thumbnail-280x405-70.jpg',
    overview: 'Grand historical novel depicting the palace conspiracies, ruthless power struggles, and eventual downfall of Jung Bahadur Rana\'s descendants.',
    genres: ['Historical Fiction', 'Political Intrigue', 'Classics'],
    pageCount: 352,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-basain',
    type: 'book',
    title: 'Basain (बसाइँ)',
    creator: 'Lil Bahadur Chettri / Chhetri (लील बहादुर क्षेत्री)',
    releaseYear: 1957,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/Basain_by_Lil_Bahadur_Chhetri-thumbnail-280x405-70.jpg',
    overview: 'A heartbreaking classic tracing the tragedy of peasant Dhane and his family, forced to abandon their ancestral home due to crushing usury.',
    genres: ['Nepali Literature', 'Social Realism', 'Classic'],
    pageCount: 62,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-radha',
    type: 'book',
    title: 'Radha (राधा)',
    creator: 'Krishna Dharabasi (कृष्ण धारावासी)',
    releaseYear: 2005,
    coverImage: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1442566736i/26598583.jpg',
    overview: 'Madan Puraskar-winning lilavadi novel reimagining Mahabharata from Radha\'s viewpoint, transforming her into an empowered philosophical voice.',
    genres: ['Nepali Literature', 'Mythology', 'Madan Puraskar'],
    pageCount: 304,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-jhola',
    type: 'book',
    title: 'Jhola (झोला)',
    creator: 'Krishna Dharabasi (कृष्ण धारावासी)',
    releaseYear: 2004,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/Jhola-front-new_1-thumbnail-280x405-70.jpg',
    overview: 'Acclaimed novella portraying the barbaric horrors of the ancient Sati tradition and a young widow\'s desperate fight for survival.',
    genres: ['Nepali Literature', 'Historical Realism', 'Short Stories'],
    pageCount: 184,
    source: 'openlibrary' as any,
  },

  // ─────────────────────────────────────────────────────────────
  // 5. Memoirs, Biographies & Existential Reflections
  // ─────────────────────────────────────────────────────────────
  {
    externalId: 'np-china-harayeko-manchhe',
    type: 'book',
    title: 'China Harayeko Manchhe (चिना हराएको मान्छे)',
    creator: 'Hari Bansha Acharya (हरिवंश आचार्य)',
    releaseYear: 2013,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/b5/China_Harayeko_Manchhe.jpg',
    overview: 'Candid and heartwarming autobiography of legendary comedian Hari Bansha Acharya, exploring childhood adversity, the loss of his wife, and resilience.',
    genres: ['Autobiography', 'Memoir', 'Comedy & Tragedy'],
    pageCount: 260,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-maha-ko-ma',
    type: 'book',
    title: 'Mahan Abhineta / MaHa ko Ma (महको म)',
    creator: 'Madan Krishna Shrestha (मदनकृष्ण श्रेष्ठ)',
    releaseYear: 2017,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/maha-ko-ma_KTwyLv2-thumbnail-280x405-70.jpg',
    overview: 'Inspiring memoir of Madan Krishna Shrestha, reflecting on five decades of comedy with Hari Bansha, pioneering inter-caste marriage, and living with Parkinson\'s.',
    genres: ['Autobiography', 'Memoir', 'Inspirational'],
    pageCount: 295,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-khusi',
    type: 'book',
    title: 'Khusi (खुसी)',
    creator: 'Vijay Kumar Pandey (विजय कुमार पाण्डे)',
    releaseYear: 2014,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/khushi-vijay-kumar-thumbnail-280x405-70.jpg',
    overview: 'Madan Puraskar-winning memoir examining journalistic power, alcohol battles, personal confessions, and the elusive pursuit of true happiness.',
    genres: ['Memoir', 'Philosophy', 'Madan Puraskar'],
    pageCount: 332,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-sambandhaharu',
    type: 'book',
    title: 'Sambandhaharu (सम्बन्धहरू)',
    creator: 'Vijay Kumar Pandey (विजय कुमार पाण्डे)',
    releaseYear: 2020,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/_Sambandhaharu_By_Vijay_Kumar-thumbnail-280x405-70.jpg',
    overview: 'Deeply introspective essays dissecting the fragility of human relationships, familial ties, betrayal, and quiet reconciliation in modern society.',
    genres: ['Philosophy', 'Essays', 'Memoir'],
    pageCount: 255,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-jiwan-kaanda-ki-phool',
    type: 'book',
    title: 'Jiwan Kaanda Ki Phool / Jiwan Kada (जीवन काँडा कि फूल)',
    creator: 'Jhamak Ghimire (झमक घिमिरे)',
    releaseYear: 2010,
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a4/Jiwan_Kada_Ki_Phool_%28book%29.jpg',
    overview: 'Madan Puraskar-winning autobiography written with her left foot, recording Jhamak Ghimire\'s extraordinary triumph against cerebral palsy and societal apathy.',
    genres: ['Autobiography', 'Inspirational', 'Madan Puraskar'],
    pageCount: 252,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-mahabir-pun',
    type: 'book',
    title: 'Samjhana, Sapana ra Abiral Yatra (सम्झना, सपना र अबिरल यात्रा)',
    creator: 'Mahabir Pun (महावीर पुन)',
    releaseYear: 2023,
    coverImage: 'https://media.thuprai.com/__sized__/front_covers/mahabir-pun-f-thumbnail-280x405-70.jpeg',
    overview: 'The inspiring autobiographical journey of Ramon Magsaysay laureate Mahabir Pun, bringing wireless internet to the Himalayas and founding the National Innovation Center.',
    genres: ['Autobiography', 'Social Innovation', 'Science'],
    pageCount: 340,
    source: 'openlibrary' as any,
  },
  {
    externalId: 'np-abstract-chintan-pyaj',
    type: 'book',
    title: 'Abstract Chintan: Pyaj (एब्स्ट्र्याक्ट चिन्तन : प्याज)',
    creator: 'Shankar Lamichhane (शंकर लामिछाने)',
    releaseYear: 1967,
    coverImage: 'https://media.thuprai.com/__sized__/products/Abstract_Chintan-thumbnail-280x405-70.jpg',
    overview: 'Madan Puraskar-winning masterwork of modernist Nepali literature, peeling layers of human consciousness and culture like the layers of an onion.',
    genres: ['Nepali Literature', 'Modernist Essays', 'Madan Puraskar'],
    pageCount: 84,
    source: 'openlibrary' as any,
  }
];

function normalizeText(text: string): string {
  return text.toLowerCase().replace(/[.,\/#!$%\^&\*;:{}=\-_`~()?"'’“”।।]/g, '').replace(/\s+/g, ' ').trim();
}

export function searchCuratedCatalog(query: string, type: 'movie' | 'tv' | 'book' | 'article'): SearchResultItem[] {
  const rawQ = query.toLowerCase().trim();
  if (!rawQ) return [];
  const cleanQ = normalizeText(rawQ);

  const catalog = type === 'book' || type === 'article' ? POPULAR_BOOKS : POPULAR_MOVIES_AND_TV;

  return catalog.filter(item => {
    const titleLower = item.title.toLowerCase();
    const creatorLower = item.creator.toLowerCase();
    const overviewLower = (item.overview || '').toLowerCase();
    
    const titleNorm = normalizeText(item.title);
    const creatorNorm = normalizeText(item.creator);
    const overviewNorm = normalizeText(item.overview || '');
    
    return titleLower.includes(rawQ) || 
           (cleanQ.length > 0 && titleNorm.includes(cleanQ)) ||
           creatorLower.includes(rawQ) || 
           (cleanQ.length > 0 && creatorNorm.includes(cleanQ)) ||
           item.genres.some(g => {
             const gLower = g.toLowerCase();
             return gLower.includes(rawQ) || (cleanQ.length > 0 && normalizeText(g).includes(cleanQ));
           }) ||
           overviewLower.includes(rawQ) || 
           (cleanQ.length > 0 && overviewNorm.includes(cleanQ));
  });
}
